POST http://localhost:8000/ HTTP/1.1
Content-Type: application/x-www-form-urlencoded
Content-Length: 27

field1=value1&field2=value2

####

POST http://localhost:8000/api HTTP/1.1


####

POST http://localhost:8000/upload HTTP/1.1
Content-Type: application/octet-stream
Transfer-Encoding: chunked

4
Wiki
5
pedia
E
 in
chunks.
0

####

POST http://localhost:8000/upload?filename=test.txt HTTP/1.1
Content-Type: application/octet-stream
Content-Length: 20

This is file content.